### ISSUE TITLE
rename package:already an archived cran package

### ISSUE THREAD

**Issue by trinker** [trinker/parser#1]

**Comment by trinker** [comment]
parsed
parse
parsr
parsesent
sentparse
parsent

**Comment by NiteshTiwari** [comment]
> if(!exists('parse_ann')) {
+   parse_ann = parse_annotator()
+ }
# **Error in parse_annotator() : could not find function "parse_annotator"**

**Comment by NiteshTiwari** [comment]
pacman::p_load_gh("trinker/parser") 
**Warning message: In pacman::p_load_gh("trinker/parser") : Failed to install/load: trinker/parser**

**Comment by trinker** [comment]
This package became parsent
